// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXP7XBLYctXX0I27-7b-bswgJjT4a2Pc',
    appId: '1:972491653683:web:9da2648b68a7c345edd946',
    messagingSenderId: '972491653683',
    projectId: 'kasir-a019e',
    authDomain: 'kasir-a019e.firebaseapp.com',
    storageBucket: 'kasir-a019e.firebasestorage.app',
    measurementId: 'G-2QDPVZJ0HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBPje2zyO0aRyEAXs2K4Typd2Xn9EwCk',
    appId: '1:972491653683:android:e63f0326e3c0745aedd946',
    messagingSenderId: '972491653683',
    projectId: 'kasir-a019e',
    storageBucket: 'kasir-a019e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0prCWtS9jJr8xL9r4r_u0QfMgqj8RhpY',
    appId: '1:972491653683:ios:06973f655313a653edd946',
    messagingSenderId: '972491653683',
    projectId: 'kasir-a019e',
    storageBucket: 'kasir-a019e.firebasestorage.app',
    iosBundleId: 'com.example.kasirOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdXP7XBLYctXX0I27-7b-bswgJjT4a2Pc',
    appId: '1:972491653683:web:7fa52a6e89d2c271edd946',
    messagingSenderId: '972491653683',
    projectId: 'kasir-a019e',
    authDomain: 'kasir-a019e.firebaseapp.com',
    storageBucket: 'kasir-a019e.firebasestorage.app',
    measurementId: 'G-6X6QNKP3MR',
  );
}
